@echo off
echo Compiling levels package (hackour.levels)...
call compile hackour/levels
echo Compiling game package (hackour.game)...
call compile hackour/game
echo Compiling devtools package (hackour.devtools)...
call compile hackour/devtools
echo Done.